In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
#menggabungkan dua array ke semua baris
np.concatenate([arr1,arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
#menggabungkan dua array ke semua kolom
np.concatenate([arr1,arr1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
#apa perbedaan antara concat dengan concatenate? 
#jadi concatenate merupakan method dari numpy sedangkan concat merupakan method dari pandas

In [6]:
#kita coba dengan menggunakan pandas
ser1 = Series([0,1,2], index=['T','U','V'])
ser2 = Series([3,4], index=['X','Y'])

In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
#di kemudian hari concat akan melakukan sorting selebih dahulu sebelum melakukan concatenate
#concat untuk axis=1 akan mengembalikan DataFrame 

#jadi axis=1 tidak benar2 menambahkan langsung satu series ke dalam series yang lain, tapi justru membuat dframe dari series tsb
pd.concat([ser1, ser2], axis=1)

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """


0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
pd.concat([ser1, ser2], axis=1, sort=False)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [12]:
pd.concat([ser1, ser2], axis=1, sort=True)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [13]:
#contoh concat axis=1 untuk dframe yang lain

In [14]:
ser3 = Series([0,2], index=['A', 'B'])
ser3

A    0
B    2
dtype: int64

In [15]:
ser4 = Series([1,2,3], index=['B','C','D'])
ser4

B    1
C    2
D    3
dtype: int64

In [16]:
#selalu menghasilkan dataframe
pd.concat([ser3,ser4], axis=1)

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


0    1
A  0.0  NaN
B  2.0  1.0
C  NaN  2.0
D  NaN  3.0

In [17]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [18]:
#keys digunakan untuk memisahkan mana yang merupakan ser1 dan mana yang merupakan ser2
pd.concat([ser1,ser2], keys=['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [19]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])

In [20]:
dframe1

X         Y         Z
0 -0.314575 -0.822870 -0.508900
1  0.149733  0.484287  0.643787
2 -2.348682  1.849230  0.440482
3  0.761832  1.342313 -0.483533

In [21]:
dframe2

Y         Q         X
0  0.884267 -0.320154 -0.073196
1  0.153481 -0.626924 -0.375649
2 -0.427179 -0.326112  0.652872

In [23]:
#semua kolom dipanggil. baris yang tidak ada kolom ybs akan bernilai null
#perhatikan indexnya, index dari dframe tersebut masih sesuai dengan dataframe sebelumnya
pd.concat([dframe1, dframe2], sort=False)

X         Y         Z         Q
0 -0.314575 -0.822870 -0.508900       NaN
1  0.149733  0.484287  0.643787       NaN
2 -2.348682  1.849230  0.440482       NaN
3  0.761832  1.342313 -0.483533       NaN
0 -0.073196  0.884267       NaN -0.320154
1 -0.375649  0.153481       NaN -0.626924
2  0.652872 -0.427179       NaN -0.326112

In [26]:
pd.concat([dframe1,dframe2], keys=['cat1', 'cat2'], sort=False)

X         Y         Z         Q
cat1 0 -0.314575 -0.822870 -0.508900       NaN
     1  0.149733  0.484287  0.643787       NaN
     2 -2.348682  1.849230  0.440482       NaN
     3  0.761832  1.342313 -0.483533       NaN
cat2 0 -0.073196  0.884267       NaN -0.320154
     1 -0.375649  0.153481       NaN -0.626924
     2  0.652872 -0.427179       NaN -0.326112

In [27]:
#concat tanpa menggunakan parameter sort, tidak ada beda, masih dframe1 dulu baru dframe2 
#indexnya pun masih sama
pd.concat([dframe1, dframe2])

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN -0.314575 -0.822870 -0.508900
1       NaN  0.149733  0.484287  0.643787
2       NaN -2.348682  1.849230  0.440482
3       NaN  0.761832  1.342313 -0.483533
0 -0.320154 -0.073196  0.884267       NaN
1 -0.626924 -0.375649  0.153481       NaN
2 -0.326112  0.652872 -0.427179       NaN

In [28]:
#ada continuous index, kalau menggunakan parameter ignore_index 
pd.concat([dframe1, dframe2], sort=False, ignore_index=True)

X         Y         Z         Q
0 -0.314575 -0.822870 -0.508900       NaN
1  0.149733  0.484287  0.643787       NaN
2 -2.348682  1.849230  0.440482       NaN
3  0.761832  1.342313 -0.483533       NaN
4 -0.073196  0.884267       NaN -0.320154
5 -0.375649  0.153481       NaN -0.626924
6  0.652872 -0.427179       NaN -0.326112

In [29]:
#For more info in documentation:
url='http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'

## Combine DataFrame

In [30]:
ser1 = Series([2, np.nan, 4, np.nan, 6, np.nan], 
             index=['Q','R','S','T','U','V'])
ser1

Q    2.0
R    NaN
S    4.0
T    NaN
U    6.0
V    NaN
dtype: float64

In [31]:
ser2 = Series(np.arange(len(ser1)), dtype=np.float64,
              index=['Q','R','S','T','U','V'])
ser2

Q    0.0
R    1.0
S    2.0
T    3.0
U    4.0
V    5.0
dtype: float64

In [32]:
#memanmbal index yang tidak dimiliki (null) oleh series1 dengan menggunakan method where
#method where untuk parameter pertama akan mengembalikan boolean, jika True maka akan diisi oleh ser2, jika False aka diisi oleh ser1
Series(np.where(pd.isnull(ser1), ser2, ser1), index=ser1.index)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [34]:
#method lainnya yang hampir mirip dengan yang diatas adalah method combine_first
#mirip dan lebih simpel
ser1.combine_first(ser2)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [35]:
nan = np.nan
dframe_odds = DataFrame({'X': [1., nan, 3., nan],
                        'Y': [nan, 5., nan, 7.],
                        'Z': [nan, 9., nan, 11.]})

In [36]:
dframe_evens = DataFrame({'X': [2.,4., nan, 6., 8.], 
                        'Y': [nan, 10.,12.,14.,16.]})

In [37]:
dframe_odds

X    Y     Z
0  1.0  NaN   NaN
1  NaN  5.0   9.0
2  3.0  NaN   NaN
3  NaN  7.0  11.0

In [38]:
dframe_evens

X     Y
0  2.0   NaN
1  4.0  10.0
2  NaN  12.0
3  6.0  14.0
4  8.0  16.0

In [39]:
#yang overlap (seperti index ke-4 di dframe_evens) tetap dimasukkan ke dalam dframe_odds
#NaN dimasukkan sesuai dengan index yang bernilai null
dframe_odds.combine_first(dframe_evens)

X     Y     Z
0  1.0   NaN   NaN
1  4.0   5.0   9.0
2  3.0  12.0   NaN
3  6.0   7.0  11.0
4  8.0  16.0   NaN

In [41]:
#mengisi nilai yang masih null dengan nilai 1
dframe_odds.combine_first(dframe_evens).fillna(1)

X     Y     Z
0  1.0   1.0   1.0
1  4.0   5.0   9.0
2  3.0  12.0   1.0
3  6.0   7.0  11.0
4  8.0  16.0   1.0

## Reshaping DataFrame

In [42]:
dframe1 = DataFrame(np.arange(8).reshape(2,4), 
                   index=pd.Index(['LA', 'SF'], name='city'),
                   columns=pd.Index(['A','B','C','D'], name='letter'))
dframe1

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [44]:
#merubah kolom menjadi rows
dframe_st = dframe1.stack()
dframe_st

city  letter
LA    A         0
      B         1
      C         2
      D         3
SF    A         4
      B         5
      C         6
      D         7
dtype: int32

In [45]:
#mengembalikan stack tsb menjadi dframe lagi
dframe_st.unstack()

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [46]:
#kita bisa melakukan usntack secara spesifik

#unstack berdasarkan letter
dframe_st.unstack('letter')

#masih tetap sama, karena pada default-nya unstack itu menggunakan kolom (?)

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [47]:
#unstack berdasarkan city 
dframe_st.unstack('city')

#maka dframe tersebut akan terbalik, row jadi kolom dan kolom jadi row 

city    LA  SF
letter        
A        0   4
B        1   5
C        2   6
D        3   7

In [48]:
#bagaimana jadinya menggunakan stack untuk index/kolom yang memiliki dua atau lebih level?
#pertanyaan yang belum terjawab

In [86]:
dframe_lvl = DataFrame(np.arange(16).reshape(4,4), index=[['a','a','b','b'], [1,2,1,2]],
                    #notice bahwa tiap index berpasangan dengan index setelahnya 
                    #misal: 'NY' pertama pasti berpasangan dengan 'cold', 'NY' kedua dengan 'hot', dst
                    #oleh karena itulah mengapa 'LA' dan 'SF' cuma memiliki satu pasangan 
                    columns=[['NY','NY','LA','SF'],['cold','hot','hot','cold']])

dframe_lvl

NY      LA   SF
    cold hot hot cold
a 1    0   1   2    3
  2    4   5   6    7
b 1    8   9  10   11
  2   12  13  14   15

In [87]:
dframe_lvl.unstack()

NY              LA       SF    
  cold     hot     hot     cold    
     1   2   1   2   1   2    1   2
a    0   4   1   5   2   6    3   7
b    8  12   9  13  10  14   11  15

In [88]:
#jadinya bentuknya aneh, masih perlu belajar lebih banyak lagi

In [49]:
#stack meng-handle null value (?)
ser1 = Series([0,1,2], index=['Q','X','Y'])

ser2 = Series([4,5,6], index=['X','Y','Z'])

In [60]:
dframe = pd.concat([ser1, ser2], keys=['Alpha', 'Beta'])
dframe

Alpha  Q    0
       X    1
       Y    2
Beta   X    4
       Y    5
       Z    6
dtype: int64

In [61]:
#mencoba kembali untuk axis=1
dframe2 = pd.concat([ser1, ser2], keys=['Alpha', 'Beta'], axis=1, sort=False)
dframe2

Alpha  Beta
Q    0.0   NaN
X    1.0   4.0
Y    2.0   5.0
Z    NaN   6.0

In [62]:
#untuk mengubah dframe tersebut menjadi DataFrame bisa menggunakan method unstack
#unstack di sini berbeda dengan concat axis=1, untuk concat axis=1 indexnya merupakan Q,X,Y,Z 
#sementara untuk dframe yang dilakukan unstack indexnya merupakan Alpha dan Beta
dframe.unstack()

Q    X    Y    Z
Alpha  0.0  1.0  2.0  NaN
Beta   NaN  4.0  5.0  6.0

In [ ]:
#kita coba cara lain

In [65]:
ser1

Q    0
X    1
Y    2
dtype: int64

In [66]:
ser2

X    4
Y    5
Z    6
dtype: int64

In [68]:
dframe3 = pd.concat([ser1, ser2])
dframe3

Q    0
X    1
Y    2
X    4
Y    5
Z    6
dtype: int64

In [70]:
#ini untuk menggunakan concat axis=1
dframe4 = pd.concat([ser1, ser2], axis=1)
dframe4

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
Q  0.0  NaN
X  1.0  4.0
Y  2.0  5.0
Z  NaN  6.0

In [77]:
#ini yang menggunakan unstack
#dframe3.unstack()

#ERROR
#kemungkinan karena tidak memiliki keys untuk memisah antara dua series

In [78]:
#balik lagi ke variabel dframe

In [79]:
dframe

Alpha  Q    0
       X    1
       Y    2
Beta   X    4
       Y    5
       Z    6
dtype: int64

In [80]:
dframe.unstack()

Q    X    Y    Z
Alpha  0.0  1.0  2.0  NaN
Beta   NaN  4.0  5.0  6.0

In [82]:
#ketika di-unstack dan stack lagi, null value sudah dihilangkan
dframe.unstack().stack()

Alpha  Q    0.0
       X    1.0
       Y    2.0
Beta   X    4.0
       Y    5.0
       Z    6.0
dtype: float64

In [83]:
#ketika kita tidak mau menghapus null value yang ada
dframe.unstack().stack(dropna=False)

Alpha  Q    0.0
       X    1.0
       Y    2.0
       Z    NaN
Beta   Q    NaN
       X    4.0
       Y    5.0
       Z    6.0
dtype: float64