In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[0:4]

array([0, 1, 2, 3])

In [5]:
arr[1:7]

array([1, 2, 3, 4, 5, 6])

In [6]:
slice_of_arr = arr[0:5]

In [7]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
slice_of_arr[:] = 100

In [10]:
slice_of_arr

array([100, 100, 100, 100, 100])

In [11]:
#hal ini karena slice_of_arr bukanlah copy dari arr, tapi view dari arr tsb
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
#untuk kopi array
arr_copy = arr.copy()

In [13]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
#array 2d
arr1d_cobaan = np.array([1,2,3,4])
arr2d_cobaan = np.array([[1,2,3,4], [4,3,2,1]])
arr2d_referensi = np.array(([1,2,3,4],[4,3,2,1]))
arr2d_3row = np.array([[1,2,3,4,5],[5,4,3,2,1],[6,7,8,9,10]])

In [15]:
arr1d_cobaan

array([1, 2, 3, 4])

In [16]:
arr2d_cobaan

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [17]:
arr2d_referensi

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [18]:
#slicing
arr2d_3row[:2,2:]

array([[3, 4, 5],
       [3, 2, 1]])

In [19]:
zero_arr = np.zeros((10,10))

In [20]:
zero_arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
zero_arr[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
arr_length = zero_arr.shape[1]

In [23]:
arr_length

10

In [24]:
arr_length2 = zero_arr.shape[1]

In [25]:
#array tidak merubah satu elemen, tapi satu list langsung
for i in range(arr_length2):
    zero_arr[i] = i

In [26]:
zero_arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [27]:
zero_arr[2]

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [28]:
zero_arr[2] = 7

In [29]:
#seharusnya menjadi 7 aja, tapi jadi [7,7,7,7,...] karena adalah fancy indexing (?)
zero_arr[2]

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])

In [30]:
zero_arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [31]:
zero_arr[[2,4,6,8]]

array([[7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [32]:
fancy_arr = np.zeros((10,10))

In [33]:
fancy_arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
fancy_arr[[2,4,6]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Array Transposition

In [35]:
arr_trans = np.arange(50).reshape(10,5)

In [36]:
arr_trans

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [37]:
#bisa dilakukan transposisi 
arr_trans.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [38]:
#perkalian array dengan dot
#5x10 (dot) 10x5 = array dengan 5x5
#jadi perkalian menggunakan fungsi dot
np.dot(arr_trans.T, arr_trans)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [39]:
# array 10x10
np.dot(arr_trans, arr_trans.T)

array([[   30,    80,   130,   180,   230,   280,   330,   380,   430,
          480],
       [   80,   255,   430,   605,   780,   955,  1130,  1305,  1480,
         1655],
       [  130,   430,   730,  1030,  1330,  1630,  1930,  2230,  2530,
         2830],
       [  180,   605,  1030,  1455,  1880,  2305,  2730,  3155,  3580,
         4005],
       [  230,   780,  1330,  1880,  2430,  2980,  3530,  4080,  4630,
         5180],
       [  280,   955,  1630,  2305,  2980,  3655,  4330,  5005,  5680,
         6355],
       [  330,  1130,  1930,  2730,  3530,  4330,  5130,  5930,  6730,
         7530],
       [  380,  1305,  2230,  3155,  4080,  5005,  5930,  6855,  7780,
         8705],
       [  430,  1480,  2530,  3580,  4630,  5680,  6730,  7780,  8830,
         9880],
       [  480,  1655,  2830,  4005,  5180,  6355,  7530,  8705,  9880,
        11055]])

In [40]:
arr3d = np.arange(50).reshape((5,5,2))

In [41]:
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [42]:
arr3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [43]:
#transpose bisa nge-reshape misal tadinya (5,5,2) kalau transpose (2,1,0) maka jadi (2,5,5); kalau transpose (1,0,2) jadi tetap
# (5,5,2) cuma ordernya berubah
arr3d.transpose((2,1,0))

array([[[ 0, 10, 20, 30, 40],
        [ 2, 12, 22, 32, 42],
        [ 4, 14, 24, 34, 44],
        [ 6, 16, 26, 36, 46],
        [ 8, 18, 28, 38, 48]],

       [[ 1, 11, 21, 31, 41],
        [ 3, 13, 23, 33, 43],
        [ 5, 15, 25, 35, 45],
        [ 7, 17, 27, 37, 47],
        [ 9, 19, 29, 39, 49]]])

In [44]:
#mengubah sumbu
arrsw = np.array([[1,2,3]])
arrsw

array([[1, 2, 3]])

In [45]:
#mengubah sumbu 0 dan 1
arrsw.swapaxes(0,1)

array([[1],
       [2],
       [3]])

## Universal Array Functions

In [48]:
arrUniv = np.arange(11)
arrUniv

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
#Melihat akar dua dari array
np.sqrt(arrUniv)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [52]:
#melihat eksponensial dari array => dari E
np.exp(arrUniv)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [53]:
#membuat rando array dengan distribusi normal (?)
A = np.random.randn(10)

A

array([-0.34911639,  0.3925476 ,  0.58708814,  0.70397369,  0.86499414,
       -2.22498879,  0.83598822, -2.3431104 , -0.65093006, -0.79499782])

In [54]:
B = np.random.randn(10)

B

array([-0.77266055,  0.72109661,  0.10526332, -2.24168532, -2.4047459 ,
       -0.08327736, -0.07856174, -0.01693349,  0.13834679,  1.06263831])

In [60]:
#binary functions, nambah dua array
X = np.add(A,B)
X

array([-1.12177694,  1.11364421,  0.69235146, -1.53771164, -1.53975176,
       -2.30826615,  0.75742648, -2.36004389, -0.51258327,  0.26764049])

In [61]:
#binary functions, lihat maksimum dari dua array
np.maximum(A,B)

array([-0.34911639,  0.72109661,  0.58708814,  0.70397369,  0.86499414,
       -0.08327736,  0.83598822, -0.01693349,  0.13834679,  1.06263831])

In [62]:
np.minimum(A,B)

array([-0.77266055,  0.3925476 ,  0.10526332, -2.24168532, -2.4047459 ,
       -2.22498879, -0.07856174, -2.3431104 , -0.65093006, -0.79499782])

In [63]:
np.maximum(A,X)

array([-0.34911639,  1.11364421,  0.69235146,  0.70397369,  0.86499414,
       -2.22498879,  0.83598822, -2.3431104 , -0.51258327,  0.26764049])