In [1]:
import numpy as np

In [3]:
my_list = [1,2,3,4]

In [4]:
my_array = np.array(my_list)

In [5]:
my_array

array([1, 2, 3, 4])

In [6]:
my_list2 = [11,22,33,44]

In [8]:
my_lists = [my_list, my_list2]

In [9]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [10]:
my_array2 = np.array(my_lists)

In [11]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [12]:
my_array2.shape()

TypeError: 'tuple' object is not callable

In [13]:
my_array2.shape

(2, 4)

In [14]:
np.zeros()

TypeError: zeros() missing required argument 'shape' (pos 1)

In [15]:
np.zeros(2,4)

TypeError: data type not understood

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
#membuat matriks identitas
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange(5,50)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

## Calculating Array

In [23]:
my_array2 * my_array2

array([[   1,    4,    9,   16],
       [ 121,  484, 1089, 1936]])

In [24]:
my_array2 - my_array2

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [25]:
1 / my_array2

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.09090909, 0.04545455, 0.03030303, 0.02272727]])

In [26]:
my_array2 ** 3

array([[    1,     8,    27,    64],
       [ 1331, 10648, 35937, 85184]], dtype=int32)

In [27]:
my_array2 * 2

array([[ 2,  4,  6,  8],
       [22, 44, 66, 88]])

In [28]:
li = [[1,2],[2,2],[3,3],[2,1]]

In [29]:
my_array3=np.array(li)

In [32]:
my_array3

array([[1, 2],
       [2, 2],
       [3, 3],
       [2, 1]])

In [33]:
my_array3.shape

(4, 2)

In [36]:
#multiplying 2x4 matrix w/ 4x2 matrix
my_array2 * my_array3
#GAK BISA

ValueError: operands could not be broadcast together with shapes (2,4) (4,2) 

In [39]:
#multiplying 4x2 matrix w/ 2x4 matrix
my_array3 * my_array2
#GAK BISA

ValueError: operands could not be broadcast together with shapes (4,2) (2,4) 